name: flock
description: pull Flock reads
datalakes:
  - name: atlas
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/org_1446ff84711242ec828df181f45e4d20
    username: atlas_user
    password: ${ATLAS_PASSWORD}
    driver: org.postgresql.Driver
  - name: flock
    url: https://api.flocksafety.com/api
    username: ${FLOCK_USER}
    password: ${FLOCK_PASSWORD}
    driver: com.flocksafety
