enable-persistence: false
session-clustering-enabled: false

hazelcast:
  server: false
  group: production
  password: openlattice
  seed-nodes:
    - ${CONDUCTOR_HOST}
  durable-executors:
    - name: _rhizome_job_service_
      pool-size: 2
      capacity: 128
      durability: 1
  scheduled-executors:
    - name: hazelcast_scheduled_tasks
      pool-size: 2
      capacity: 128
      durability: 1

hazelcast-clients:
  IDS:
    server: false
    group: production
    password: openlattice
    seed-nodes:
      - ${CONDUCTOR_HOST}

postgres:
  initialize-indices: false
  initialize-tables: false
  citus: false
  hikari:
    jdbcUrl: jdbc:postgresql://${POSTGRESQL1_HOST}:5432/alprs?sslmode=require
    username: alprs_user
    password: ${ALPRS_PASSWORD}
    maximumPoolSize: 100
    connectionTimeout: 120000
