postgres:
  config:
    jdbcUrl: jdbc:postgresql://${POSTGRESQL1_HOST}:5432/alprs?sslmode=require
    username: alprs_user
    password: ${ALPRS_PASSWORD}
    maximumPoolSize: 1
    connectionTimeout: 120000
aurora:
  config: {}
alpr:
  config: {}
